# Generated by Django 4.1.4 on 2022-12-31 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('DI', 'Directory'), ('MA', 'Management'), ('DE', 'Department'), ('TE', 'Team')], default='MA', max_length=2)),
                ('parant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='od.section')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('schedule', models.CharField(choices=[('FT', 'Full-Time'), ('PT', 'Part-Time'), ('ST', 'Shift')], default='FT', max_length=2)),
                ('level', models.CharField(choices=[('SR', 'Senior'), ('MD', 'Middle'), ('JR', 'Junior'), ('GR', 'Graduate')], default='GR', max_length=2)),
                ('description', models.TextField(blank=True)),
                ('responsibilities', models.TextField(blank=True)),
                ('requirement', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='od.section')),
            ],
            options={
                'verbose_name': '',
                'verbose_name_plural': 's',
            },
        ),
    ]
