# Generated by Django 4.1.4 on 2022-12-31 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('od', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='parant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='od.section'),
        ),
    ]
